### ISSUE TITLE
SSO untuk Mahasiswa FK Program Profesi

### ISSUE THREAD

**Issue by ariefpurnamamuharram** [RistekCSUI/SSO#10]
Selamat malam, 
Saya Arief Purnama Muharram, dari FKUI. Saya sedang membuat prototipe sistem dengan _library SSO_. Sepertinya SSO belum bisa digunakan untuk mahasiswa program profesi? Ketika _login_ dengan akun mahasiswa profesi mengalami _error_. Mohon bantuannya.
Terima kasih.

![Screenshot (307)](https://user-images.githubusercontent.com/16641165/62703482-8df06e00-ba13-11e9-8d43-97ad841a20a2.png)

**Comment by imiro** [comment]
Saya pernah mengalami hal yang sama. 

Library ini tidak dapat digunakan untuk program profesi karena `$user->org_code` akan berbentuk array (mahasiswa program profesi memiliki 2 role, satu sebagai mahasiswa sarjana, satu sebagai mahasiswa profesi). 

Bisa dihandle dengan menambahkan satu kondisional di line 130 tersebut, jika `$user->org_code` berbentuk array.
