### ISSUE TITLE
getAttributes cant/fail to fetch details

### ISSUE THREAD

**Issue by ghost** [RistekCSUI/SSO#7]
mungkin SSO sudah tidak memberikan informasi terhadap orang yang login. phpCAS::getAttributes()  mengembalikan array berisikan nil. oh iya, sebelumnya method ini mengembalikan attribute2 yang sesuai dengan dokumentasi

**Comment by bobbypriam** [comment]
cc: @jundialwan UI udah ga buka data SSO lagi kah?

**Comment by jundialwan** [comment]
Wah sepertinya perlu saya cek dulu
Belum dengar kabar-kabar data gak dibuka lagi sih

**Comment by jundialwan** [comment]
@dayatbflash Saya coba barusan ternyata juga tidak bisa untuk semua cas2, cas3, cas4. Setelah tanya-tanya dari beberapa sumber sepertinya SSO sedang diupdate sistem nya untuk cas2, cas3, cas4 dari beberapa waktu lalu. Jadi ditunggu saja.

Akan saya update disini lagi kalau sudah up atau ada kabar lain.
Thanks!

**Comment by jundialwan** [comment]
@dayatbflash @bobbypriambodo sepertinya sudah kembali seperti semula. Saya sudah bisa fetch data dari SSO tanpa ada perubahan. 

Thanks all!
CASE CLOSED
